name: teste_lixeiras

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8
  percent_indicator: ^4.2.2
  shared_preferences: ^2.1.1
  http: ^1.2.2
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

 uses-material-design: true
 assets:
   - assets/ScanMe.png